### ISSUE TITLE
Cannot build Android on Windows

### ISSUE THREAD

**Issue by markkhoo** [sfbrigade/intentional-walk#204]
Having and issue running the Android build on Windows. After passing through several issues, I receive the following error.

```shell
> IntentionalWalkApp@0.0.1 android C:\Users\Kimar\Desktop\SF-Brigade\intentional-walk
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1246 file(s) to forward-jetify. Using 24 workers...
info JS server already running.
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 460ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 460ms

    at makeError (C:\Users\Kimar\Desktop\SF-Brigade\intentional-walk\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\Kimar\Desktop\SF-Brigade\intentional-walk\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! IntentionalWalkApp@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the IntentionalWalkApp@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kimar\AppData\Roaming\npm-cache\_logs\2021-09-23T03_44_35_905Z-debug.log
```

**Comment by francisli** [comment]
@markkhoo the error says it cannot find any emulators or connected devices. If you haven't done so already, launch Android Studio and use the AVD Manager to set up a virtual device emulator. Or, enable developer mode on an Android phone and connect it via USB...
